[build]
    command = "npm run build"
    publish = "dist"

[dev]
    framework = "#custom"
    command = "npm run dev"
    targetPort = 9000
    port = 8080
    publish = "dist" 
    autoLaunch = true